# ============================================================
# Layer 1: Base system + Python packages (changes rarely)
# ============================================================
FROM python:3.11-slim AS base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install runtime Python packages (cached unless requirements.txt changes)
COPY requirements-runtime.txt .
RUN pip install --no-cache-dir -r requirements-runtime.txt

# ============================================================
# Layer 2: Runtime application (changes frequently)
# ============================================================
FROM base AS runtime

# Copy application code
COPY app/ ./app/
COPY templates/ ./templates/
COPY main.py .
COPY requirements-runtime.txt .

# Install runtime dependencies
RUN pip install --no-cache-dir -r requirements-runtime.txt

# Pre-built data should exist (generated by build_index.py on host)
COPY data/ ./data/

EXPOSE 8000

CMD ["python", "main.py"]

# ============================================================
# Layer 3: Build image (for index generation)
# ============================================================
FROM base AS builder

# Install build dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app/ ./app/
COPY build_index.py .

# Default command - will be overridden by docker-compose
CMD ["python", "build_index.py", "--help"]
