FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy and install runtime dependencies
COPY requirements-runtime.txt .
RUN pip install --no-cache-dir -r requirements-runtime.txt

# Copy application code
COPY app/ ./app/
COPY templates/ ./templates/
COPY main.py .

# Pre-built data should exist (generated by build_keywords.py on host)
COPY data/ ./data/

EXPOSE 8000

CMD ["python", "main.py"]
